namespace Medallion.Threading;

public interface IDistributedUpgradeableReaderWriterLockProvider : IDistributedReaderWriterLockProvider
{
	IDistributedUpgradeableReaderWriterLock CreateUpgradeableReaderWriterLock(string name);
}
