using System;
using System.Runtime.Serialization;

namespace Microsoft.AppCenter.Crashes;

[Serializable]
public class TestCrashException : Exception
{
	private const string CrashMessage = "Test crash exception generated by SDK";

	protected TestCrashException(SerializationInfo info, StreamingContext context)
		: base(info, context)
	{
	}

	public TestCrashException()
		: base("Test crash exception generated by SDK")
	{
	}
}
